version: '3.8'

services:
  app:
    build: .
    container_name: integrar-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./wait-for-it.sh:/wait-for-it.sh
    working_dir: /var/www/html
    ports:
      - "8081:8000"
    command: >
      sh -c '
        chmod +x /wait-for-it.sh &&
        /wait-for-it.sh db:3306 --timeout=60 --strict -- \
        sh -c "if [ ! -f artisan ]; then \
          composer create-project laravel/laravel temp-laravel --prefer-dist; \
          cp -r temp-laravel/* .; \
          cp -r temp-laravel/.* . 2>/dev/null || true; \
          rm -rf temp-laravel; \
          chmod -R 777 storage bootstrap/cache; \
        fi; \
        php artisan serve --host=0.0.0.0 --port=8000"
      '
    user: root
    environment:
      - UID=${UID}
      - GID=${GID}
      - TZ=America/Sao_Paulo
    networks:
      - integrar-net
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: integrar-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: integrar
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - integrar-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: integrar-phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: secret
    networks:
      - integrar-net
    depends_on:
      - db

networks:
  integrar-net:

volumes:
  mysql_data:
